/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InterestCalc {
        "checked": string;
    }
}
declare global {
    interface HTMLInterestCalcElement extends Components.InterestCalc, HTMLStencilElement {
    }
    var HTMLInterestCalcElement: {
        prototype: HTMLInterestCalcElement;
        new (): HTMLInterestCalcElement;
    };
    interface HTMLElementTagNameMap {
        "interest-calc": HTMLInterestCalcElement;
    }
}
declare namespace LocalJSX {
    interface InterestCalc {
        "checked"?: string;
    }
    interface IntrinsicElements {
        "interest-calc": InterestCalc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "interest-calc": LocalJSX.InterestCalc & JSXBase.HTMLAttributes<HTMLInterestCalcElement>;
        }
    }
}
