/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InterestCalc {
    }
    interface InterestResult {
    }
}
declare global {
    interface HTMLInterestCalcElement extends Components.InterestCalc, HTMLStencilElement {
    }
    var HTMLInterestCalcElement: {
        prototype: HTMLInterestCalcElement;
        new (): HTMLInterestCalcElement;
    };
    interface HTMLInterestResultElement extends Components.InterestResult, HTMLStencilElement {
    }
    var HTMLInterestResultElement: {
        prototype: HTMLInterestResultElement;
        new (): HTMLInterestResultElement;
    };
    interface HTMLElementTagNameMap {
        "interest-calc": HTMLInterestCalcElement;
        "interest-result": HTMLInterestResultElement;
    }
}
declare namespace LocalJSX {
    interface InterestCalc {
    }
    interface InterestResult {
    }
    interface IntrinsicElements {
        "interest-calc": InterestCalc;
        "interest-result": InterestResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "interest-calc": LocalJSX.InterestCalc & JSXBase.HTMLAttributes<HTMLInterestCalcElement>;
            "interest-result": LocalJSX.InterestResult & JSXBase.HTMLAttributes<HTMLInterestResultElement>;
        }
    }
}
